### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by Leoportilla** [ahmedbarakat2007/Ziunx-Emu#1]
Ele inicia bem em alguns jogos, porem parece que apos umas partidas ele começa a dar umas travadas, o odissey estava muito bom e o mario kart tambem, mas logo depois ficou meio lento, uma ideia boa seria uma repaginada nos logos e layout,

**Comment by ahmedbarakat2007** [comment]
the crash is caused because the game is too heavy on your gpu + we think about that :3

**Comment by Leoportilla** [comment]
é um s23 ultra 8gen 2, o zelda esta rodando muito bem, e o odissey até esta legal, o fighter z continua com glits na barra grafica, não sei o que estão fazendo mas esta dando certo, espero que os boatos de virus sejam boatos, e todo sucesso desejamos.

**Comment by Leoportilla** [comment]
Bomber man 2 não abre, essa alteração tem no sudachi novo. Vocês conseguem fazer funcionar jogos novos?

**Comment by Leoportilla** [comment]
me baniram do grupo do telegram sem motivo nenhum? nem se quer se pode comentar la? por que

**Comment by ahmedbarakat2007** [comment]
First ofcourse not everygame works you can say only 1% of games doesn't work and interms of you being banned from the channel this is not true but the channel got hacked and we had to make a new channel
link : https://t.me/zinux1
spread this link if you can :)
