### ISSUE TITLE
Game crash after main menu, please help

### ISSUE THREAD

**Issue by Elludan** [ahmedbarakat2007/Ziunx-Emu#2]
Al salam Alikum

First of All, thank you for your hard work and effort, much appreciated.

I kindly ask for your help. I am trying to emulate shin megami tensei V on my android, but i crash after i start a new game. 

Im using 0.4 resolution and i have 40 to 50 fps in the main menu. When i click on start new game, the fps gradually drops to zero before crashing. Is this a problem in my downloaded NSP file or is it a problem in my phone?

Im using Redmi note 13 pro 4g version with Helio g99 ultra processor. Many thanks for your help.

**Comment by Mrcatsen** [comment]
Im also want to know if this emulator work on samsung s20 ..prossecor Exonys 990 Mali G77 andriod 13

**Comment by ahmedbarakat2007** [comment]
some games doesn't work properly on the emu but we are working hard on all these issues and it will be fixed soon
