### ISSUE TITLE
Game freeze after playing couple of minutes 

### ISSUE THREAD

**Issue by ProDanTe69** [ahmedbarakat2007/Ziunx-Emu#7]
After 2 minutes of playing dragon Ball fighterz. The Game is freezing randomly during a fight. Everything will freeze, but the music will still play. Fix this

**Comment by ahmedbarakat2007** [comment]
gpu driver issue or maybe your gpu is too weak

**Comment by JuAnCa522** [comment]
The same thing happens to me in FIFA 18 sn 720g 4g ram

**Comment by ahmedbarakat2007** [comment]
> The same thing happens to me in FIFA 18 sn 720g 4g ram

try different gpu driver

**Comment by ProDanTe69** [comment]
> gpu driver issue or maybe your gpu is too weak

I have 8+gen1...i tried all drivers.. still freezing
